#Basic model fit using scipy curve_fit

from scipy.optimize import curve_fit
import numpy as np
def actual_model(x):
    y=(x**3) - (2*x) +4
    return y
    

def test_model(x,a,b,c):
    y=x**a - b*x + c
    return y  
inx=np.linspace(0,100,num=50)
print(inx)
daty=np.linspace(0,100,num=50)
sdy=np.linspace(0,100,num=50) #adding some random standard deviations in data
for i in range(0,len(inx)):
    daty[i]=actual_model(inx[i]) + (np.random.randint(low=0,high=2)*0.00001)
    sdy[i]=(daty[i]/10.)+ (np.random.randint(low=-1,high=1)*0.00000001) 
 
print('Fit without boundaries using least square')       
popt,pcov=curve_fit(test_model,inx,daty)                                                 
print(popt)
print(pcov)
print('Fit with boundaries using TRF')       
popt,pcov=curve_fit(test_model,inx,daty,sigma=sdy,method='trf',bounds=([0,0,0],[5,5,5]))      
print(popt)
print(pcov)
print('Fit with boundaries using Dog-leg/dogbox')       
popt,pcov=curve_fit(test_model,inx,daty,sigma=sdy,method='dogbox',bounds=([0,0,0],[5,5,5]))
print(popt)
print(pcov)
'''
Note
---------------------------
This is just fake data generated by a function. In real experimental data analysis, for more
reliable results you may want to add the standard deviation of your observations.


The results from curve_fit are quite good but due to random numbers included in generating the data,
you may see slight difference in results in every run. In actual data with fixed points, 
this should not be a problem.
----------------------------------------------------

HW Tasks:
-------------------------------

A) Use hba1c_fake data file  and fit a model for HbA1C using single dependent variable 
Triglycerides. You can create any model of your choice with any boundary conditions
with maximum 3 parameters to fit (a,b,c). You do not have sigma points in that data set so no need 
to use it.

B) Perform error analysis using:
    Error=Sum((y_data - y_model)^2)
    where y_data is actual HbA1C against Triglucerides  and y_model is predicted data against Triglucerides.
    The sum will be over all the data points used in the analysis. 
    
    I am not checking for the best model, I just need to you to go through the process.

'''                                             
                                                                                                                                       


